[package]
name = "bluest-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bluest = "0.6.6"
futures = "0.3.30"
tokio = {vesion = "1.36.0", features = ["full"] }
